name: hey_just_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_rich_text: '^2.0.0'
  lottie: ^2.2.0

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.4
  kakao_flutter_sdk: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - lottie/

  fonts:
    - family: PreBd
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
    - family: PreRg
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
    - family: Gangwon
      fonts:
        - asset: assets/font/GangwonStrong.ttf



