name: hey_just_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PreBd
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
    - family: PreRg
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
    - family: Gangwon
      fonts:
        - asset: assets/font/GangwonStrong.ttf
