name: hey_just_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0
  url_launcher: ^6.2.4
  kakao_flutter_sdk: ^1.8.0
  kakao_flutter_sdk_share: ^1.8.0
  fluttertoast: ^8.2.4
  http: ^1.2.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
  fonts:
    - family: PreBd
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
    - family: PreRg
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
    - family: Gangwon
      fonts:
        - asset: assets/font/GangwonStrong.ttf
